<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>warnings</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefaultItemExcludes>packages/**</DefaultItemExcludes>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=.\</PathMap>
    </PropertyGroup>

    <PropertyGroup>
        <GodotPath>/home/hex3/Documents/modding/STS2/Godot_v4.5.1-stable_mono_linux.x86_64</GodotPath>
        <Sts2Path>/home/hex3/.steam/steam/steamapps/common/Slay the Spire 2/</Sts2Path>
        <ModsPath>$(Sts2Path)/mods/</ModsPath>
        <Sts2DataDir>$(Sts2Path)/data_sts2_linuxbsd_x86_64</Sts2DataDir>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);MSB3270</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')">
        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Publicize Include="sts2" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Alchyr.Sts2.BaseLib" Version="3.1.8" PrivateAssets="All" />
        <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="*" />
        <AdditionalFiles Include="BuffTheSpire/localization/**/*.json" />
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include=".gitignore" />
        <None Include="BuffTheSpire.json" />
        <None Include="project.godot" />
        <None Include="BuffTheSpire/**" />
    </ItemGroup>
    
    <Target Name="CheckDependencyPaths">
        <Error Text=" Slay the Spire 2 data not found at path '$(Sts2DataDir)'" Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')" />
        <Error Text=" Godot not found at path '$(GodotPath)'" Condition="'$(GodotPath)' == '' or !Exists('$(GodotPath)')" />
    </Target>
    
    <Target Name="CopyToModsFolderOnBuild" AfterTargets="PostBuildEvent">
        <Message Text="Copying .dll and manifest to mods folder." Importance="high" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" />
        <Copy SourceFiles="BuffTheSpire.json" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" />
        <Message Text="Copying BaseLib to mods folder." Importance="high" />
        <ItemGroup>
            <BaseLibFiles Include="packages/alchyr.sts2.baselib/**/lib/**/BaseLib.dll;packages/alchyr.sts2.baselib/**/Content/BaseLib.pck;packages/alchyr.sts2.baselib/**/Content/BaseLib.json;" />
        </ItemGroup>
        <Copy SourceFiles="@(BaseLibFiles)" DestinationFolder="$(ModsPath)BaseLib/" />
    </Target>

    <Target Name="GodotPublish" AfterTargets="PostBuildEvent" Condition="'$(GodotPath)' != '' and Exists('$(GodotPath)') and '$(IsInnerGodotExport)' != 'true'">
        <Message Text="Exporting Godot .pck to mods folder" Importance="high" />
        <Exec Command="&quot;$(GodotPath)&quot; --headless --export-pack &quot;BasicExport&quot; &quot;$(ModsPath)$(MSBuildProjectName)/$(MSBuildProjectName).pck&quot;" EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1" ContinueOnError="WarnAndContinue" />
    </Target>

    <Target Name="GodotPublishSkipped" AfterTargets="PostBuildEvent" Condition="'$(GodotPath)' == '' or !Exists('$(GodotPath)')">
        <Message Text="Skipping Godot .pck export because GodotPath is not configured." Importance="high" />
    </Target>
</Project>
